### ISSUE TITLE
Cause contract inconsistent with Plaid API

### ISSUE THREAD

**Issue by bessdt** [viceroypenguin/Going.Plaid#122]
The `cause` object returned in Plaid API is documented as:

```yml
    Cause:
      title: Cause
      type: object
      additionalProperties: true
      allOf:
      - $ref: '#/components/schemas/PlaidError'
      - type: object
        properties:
          item_id:
            $ref: '#/components/schemas/ItemId'
      required:
      - item_id
      - error_type
      - error_code
      - error_message
      - display_message
      description: An error object and associated `item_id` used to identify a specific Item and error when a batch operation operating on multiple Items has encountered an error in one of the Items.
```

On the Going.Plaid cause object, this is implemented as:

```csharp
public record Cause
{
	/// <summary>
	/// <para>The <c>item_id</c> of the Item associated with this webhook, warning, or error</para>
	/// </summary>
	[JsonPropertyName("item_id")]
	public string ItemId { get; init; } = default!;

	/// <summary>
	/// 
	/// </summary>
	[JsonPropertyName("error")]
	public Errors.PlaidError? Error { get; init; } = default!;
}
```

I believe it should be implemented as:
```csharp
public record Cause : PlaidError
{
	/// <summary>
	/// <para>The <c>item_id</c> of the Item associated with this webhook, warning, or error</para>
	/// </summary>
	[JsonPropertyName("item_id")]
	public string ItemId { get; init; } = default!;
}
```

I would PR this change but I wasn't able to get your tests working.  Any contribution guide or setup requirements?

**Comment by viceroypenguin** [comment]
Thanks for letting me know. I have several things to say, so I'll break them out separately.

1. First, to run tests, all you need to do is add a `secrets.json` to the Plaid.Tests project, with your clientid and sandbox secret. There are no global demo keys available, so for you to test, you'll need to use your personal api keys.
2. Modifying Plaid is a tricky situation, because I automate building items from the yml file. If you do decide to take a look, you'll have to use Plaid.OpenApiParser to generate files from the yml, and then track differences to ensure that they are all valid (there are a few things that I have to revert and I just haven't updated the automation to handle them properly, such as `CreditRelayGetAsync` returning an `AssetReport.` entity).
3. `Cause` was weird when I originally wrote it. `Error` held multiple `Cause`s, and each of those held an `Error`. However, the recursive loop was confusing the parser, so I was manually fixing it up each release. I did not realize that Plaid had cleaned up the hierarchy since I kludged it together.
4. Updated w/ 8f832f4. I'll release it with the next release, which will be whenever Plaid puts out a new yml file.

**Comment by bessdt** [comment]
@viceroypenguin Thanks for the heads up and quick response.  Appreciate your work here!

**Comment by viceroypenguin** [comment]
@bessdt New release v4.20.0 includes this fix.
