### ISSUE TITLE
AccessToken is sent when using ExchangePublicTokenAsync 

### ISSUE THREAD

**Issue by sebastienlabine** [viceroypenguin/Going.Plaid#239]
When using the ExchangePublicTokenAsync endpoint, Plaid error returns
`the following fields are not recognized by this endpoint: access_token
`

From what I can see, you set accessToken at the creation of the PlaidClient, which seems to be the cause of my error:
[Going.Plaid/src/Plaid/PlaidClient.cs]

(https://github.com/viceroypenguin/Going.Plaid/blob/fdaa42fe096e85265e3e921e16ccc0e2a94a8d2e/src/Plaid/PlaidClient.cs#L77)

This seems to oveeride the per request config.

**Comment by viceroypenguin** [comment]
Please provide the code that you are using that experiences this issue.

**Comment by sebastienlabine** [comment]
```c#        

_client = new Going.Plaid.PlaidClient(_config.Environment, _config.ClientId, _config.ClientSecret);

public async Task<ItemPublicTokenExchangeResponse> ExchangePublicTokenAsync(ItemPublicTokenExchangeRequest request)
        {
            request.AccessToken = null;

            var response = await _client.ItemPublicTokenExchangeAsync(request));

            if (!response.IsSuccessStatusCode)
            {
                throw new PlaidAPIException(response.Error);
            }
            return response;
        }
`

if you remove the request.accessToken, the request fails

**Comment by viceroypenguin** [comment]
Sounds like you're misunderstanding the purpose of `protected internal override bool IncludeAccessToken => false;`. 

The goal of that property is to inform `PlaidClient` whether to take the access token that is saved with `PlaidClient` and _add_ it to the `request`. It does not _remove_ `AccessToken` if you have provided that value. In this case, _you_ are adding `AccessToken` to the `request`. The fix is to either stop adding it to the `request`, or as in this case, remove it by setting it to `null`.

**Comment by sebastienlabine** [comment]
@viceroypenguin Sorry if I wasn't clear enough. The code that I showed right there is the **fix** I implemented in order to force the serializer not to include the accessToken in the request. As stated, if you remove `request.AccessToken  = null`, the request will **fail**, even though I haven't joined any accessToken.

**Comment by viceroypenguin** [comment]
Sorry, I put this on my todo list and then promptly forgot. 

I have written some testing code, and I am not able to replicate your concern.

Consider the following code:
```cs
var client = new PlaidClient(
	Going.Plaid.Environment.Development, 
	clientId: "123", 
	secret: "456", 
	accessToken: "789"
);
await client.ItemPublicTokenExchangeAsync(
	new() { PublicToken = "abc", }
);
```

When running this, I get the following request made to the Plaid servers:
```
POST https://development.plaid.com/item/public_token/exchange HTTP/1.1
Host: development.plaid.com
Plaid-Version: 2020-09-14
Accept-Encoding: gzip, deflate, br
Content-Type: application/json; charset=utf-8
Content-Length: 55

{"public_token":"abc","secret":"456","client_id":"123"}
```

Note that the `access_token` of `"789"` is not present in that json. 

This tells me that whatever you are doing on your side, you are explicitly setting `request.AccessToken`, which is why you have to do `request.AccessToken = false;`. 

I will also note that in your code snippet [here](https://github.com/viceroypenguin/Going.Plaid/issues/239#issuecomment-2150295432), you are creating a new `_client`, but are not passing an `accessToken` to it. By definition, if the `_client` does not have an access token, then it cannot set it. You are resetting the `request.accessToken = null` before even creating the `_client`. 

I will say again: `IncludeAccessToken => false` does not mean that `PlaidClient` will _remove_ the `AccessToken`. It only informs whether the library will _add_ `AccessToken` to the object if it is not provided. If you provide a `request` that includes an already set `AccessToken`, then Going.Plaid will send the `AccessToken`.

**Comment by viceroypenguin** [comment]
Closing for lack of further response. Please reopen if you have any further concerns, @sebastienlabine.
