### ISSUE TITLE
Plaid return Security with Type = null, make the Going Plaid throw exception.

### ISSUE THREAD

**Issue by trongminhtran** [viceroypenguin/Going.Plaid#48]
Hi Admin,
I'm using the Going.Plaid version 2.8.0 and take the issue when Plaid return Security with Type = null. Please help to take a look to the issue, thanks.

How: execute get Investment Holding
Issue:  Plaid return Security with type = null and Going.Plaid throw exception  **Expected a non-null enum value, found null.**

{
      "close_price": null,
      "close_price_as_of": null,
      "cusip": null,
      "institution_id": null,
      "institution_security_id": null,
      "is_cash_equivalent": false,
      "isin": null,
      "iso_currency_code": "USD",
      "name": null,
      "proxy_security_id": null,
      "security_id": "PDRMBVM8r3t5BA9NmJdKfPolGqlg8dtEGB37n",
      "sedol": null,
      "ticker_symbol": "PZ8XP9000",
      **"type": null,**
      "unofficial_currency_code": null
    },

**Comment by viceroypenguin** [comment]
@trongminhtran  - do me a favor, try 3.0.0-preview5? I'm not doing any active work on 2.8 anymore, since I'm trying to work towards having a more complete and automated version of the library based on the spec that is published by Plaid. I checked this property and it is marked `string?` in 3.0.0-preview5.

**Comment by viceroypenguin** [comment]
I'd like to get a few more unit tests in before I'm confident saying it's good for everyone. Hopefully this weekend!
